import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} bg-white min-h-screen text-gray-700`}
      >
        <Navbar />
        {children}
        <script
          src={process.env.NEXT_PUBLIC_FONTAWESOME_KIT}
          crossOrigin="anonymous"
        ></script>
      </body>
    </html>
  );
}
